server:
  port: 18092

spring:
  profiles:
    active: dev
  application:
    name: xc_cms_manage_cms-client
  data:
    mongodb:
      uri: mongodb://xc_user:123456@localhost:27017/xc_cms
      database: xc_cms
      username: xc_user
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 1303f1ae-4167-40e9-86ee-a6907583be78
        group: xc
        metadata:
          version: 1.0.0  # 元数据，可以定义任意KV，用于灰度发布、蓝绿部署等场景
        # 心跳和超时设置
        heartbeat-interval: 5000  # 心跳间隔时间，单位为毫秒，默认5秒
        watch-delay: 1000  # 服务列表更新间隔时间，默认1秒
        register-enabled: true  # 是否开启服务注册，默认是 true
        enabled: true  # 是否启用 Nacos 服务发现
        secure: false  # 是否使用 https 连接
#        access-key: your-access-key  # 鉴权配置（可选，如果 Nacos 开启鉴权）
#        secret-key: your-secret-key  # 鉴权密钥（可选）
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  freemarker:
    cache: false # 关闭模版缓存
    settings:
      template_update_delay: 0

  rabbitmq:
    host: 127.0.0.1
    port: 5673
    username: admin
    password: admin
    virtual-host: /

xuecheng:
  mq:
    # cms客户端监控的队列名称（不同客户端监控的队列名称不能重复）
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1 # 此rotingKey为门户站点ID